version: '3'

services:
  backend:
    build:
      context: ./back-end
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:3000"
